version: '3.1'

services:
  db:
    image: mysql
    platform: linux/amd64 #i use M1
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: dataminr
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: admin
    ports:
      - 3309:3306
      #MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./src/clients/mysql/schema:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080